pipeline {
    agent none
    stages {
        stage("Docker"){
            agent { label 'master' }
            steps {
                sh 'docker run --name maven -t -d -v ./.m2/:/root/.m2 -w /var/lib/jenkins/workspace/simple-java-maven-app -v /var/lib/jenkins/workspace/simple-java-maven-app:/var/lib/jenkins/workspace/simple-java-maven-app:rw,z -v /var/lib/jenkins/workspace/simple-java-maven-app@tmp:/var/lib/jenkins/workspace/simple-java-maven-app@tmp:rw,z maven:3.9.2 cat'
                sh 'docker exec -i maven mvn -B -DskipTests clean package'
                sh 'docker exec -i maven mvn test'
                sh 'docker exec -i maven ./jenkins/scripts/deliver.sh'
                sh 'docker stop maven'
                sh 'docker rm maven'
            }
        }
        stage("Copy"){
            agent { label 'master' }
            steps {
                sh 'scp /var/lib/jenkins/workspace/simple-java-maven-app/target/my-app-1.0-SNAPSHOT.jar ubuntu@172.20.38.139:/home/ubuntu'
            }
        }
        stage("Deploy"){
            agent { label 'node-1' }
            steps {
                sh 'java -jar /home/ubuntu/my-app-1.0-SNAPSHOT.jar'
            }
        }        
    }
}
